name: ✨ Feature Request
description: 새로운 기능이나 개선 사항을 제안할 때 사용하세요
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: input
    id: summary
    attributes:
      label: 요약
      description: 어떤 기능을 제안하는지 간단히 써주세요
      placeholder: ex. 다크 모드 지원 추가
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: 제안 배경
      description: 이 기능이 왜 필요한지, 어떤 문제를 해결하려는 건지 설명해주세요
      placeholder: ex. 사용자들이 야간에 눈이 피로하다고 느낍니다.
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 제안 내용
      description: 기능이 어떻게 동작하길 원하는지 구체적으로 써주세요
      placeholder: ex. 설정에서 다크 모드를 켜면 배경이 어두운 색상으로 전환되고...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 고려한 대안
      description: 혹시 고려했던 다른 방법이 있다면 작성해주세요
      placeholder: ex. 밝기 조절 기능도 검토했지만, 다크 모드가 더 효율적이라 판단했습니다.

  - type: textarea
    id: etc
    attributes:
      label: 기타
      description: 추가로 참고할 내용이 있다면 작성해주세요
